"""
llms.txt generator — structured site description for AI agents.
Based on llmstxt.org spec.
"""
from geo_optimizer.core.crawler import CrawlResult


def generate_llms_txt(crawl: CrawlResult) -> str:
    name = crawl.business_name or crawl.domain
    description = crawl.description or ""

    lines = [
        f"# {name}",
        "",
        f"> {description}" if description else f"> {name}",
        "",
    ]

    # Contact section
    contact_items = []
    if crawl.phone:
        contact_items.append(f"- Phone: {crawl.phone}")
    if crawl.email:
        contact_items.append(f"- Email: {crawl.email}")
    if crawl.address:
        contact_items.append(f"- Address: {crawl.address}")

    if contact_items:
        lines.append("## Contact")
        lines.extend(contact_items)
        lines.append("")

    # Social / Links
    if crawl.social:
        lines.append("## Links")
        for platform, url in crawl.social.items():
            lines.append(f"- [{platform.capitalize()}]({url})")
        lines.append("")

    # Site URL
    lines.append("## Website")
    lines.append(f"- [{crawl.domain}]({crawl.url})")
    lines.append("")

    lines.append("<!-- Generated by geo-optimizer (causabi.com) -->")

    return "\n".join(lines)
